# Generated by Django 2.2 on 2020-10-31 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesbase',
            name='course_num',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='coursesbase',
            name='course_pic',
            field=models.FileField(blank=True, default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='coursesbase',
            name='level_name',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='coursesbase',
            name='course_name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
