# Generated by Django 2.2 on 2020-10-31 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0003_auto_20201031_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesbase',
            name='course_num',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='coursesbase',
            name='course_pic',
            field=models.FileField(blank=True, default='/', upload_to=''),
        ),
    ]
