# Generated by Django 2.2 on 2020-10-31 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0004_auto_20201031_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesbase',
            name='course_num',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='coursesbase',
            name='course_pic',
            field=models.FileField(default='/', upload_to=''),
        ),
        migrations.AlterField(
            model_name='coursesbase',
            name='level_name',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
