# Generated by Django 2.2 on 2020-10-31 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0005_auto_20201031_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesbase',
            name='course_pic',
        ),
    ]
