# Generated by Django 2.2 on 2020-10-31 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0006_remove_coursesbase_course_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesbase',
            name='course_num',
            field=models.IntegerField(),
        ),
    ]
