# Generated by Django 2.2 on 2020-10-31 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0007_auto_20201031_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesbase',
            name='course_pic',
            field=models.FileField(blank=True, default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='coursesbase',
            name='course_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='coursesbase',
            name='course_num',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='coursesbase',
            name='level_name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
