# Generated by Django 2.2 on 2020-10-31 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0012_auto_20201031_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesbase',
            name='course_num',
        ),
    ]
