# Generated by Django 2.2 on 2020-10-31 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0013_remove_coursesbase_course_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesbase',
            name='course_pic',
        ),
        migrations.RemoveField(
            model_name='coursesbase',
            name='level_name',
        ),
    ]
