# Generated by Django 2.2 on 2020-10-31 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0014_auto_20201031_1621'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoursesBase',
        ),
    ]
