# Generated by Django 2.2 on 2020-10-31 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0015_delete_coursesbase'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseid', models.CharField(max_length=4)),
                ('course_name', models.CharField(max_length=50)),
                ('lessonid', models.CharField(blank=True, max_length=2)),
                ('lesson_name', models.CharField(blank=True, max_length=50)),
                ('icon', models.FileField(upload_to='')),
                ('description', models.CharField(blank=True, max_length=5000)),
                ('video', models.FileField(blank=True, upload_to='')),
            ],
        ),
    ]
