# Generated by Django 2.2 on 2020-11-21 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0017_auto_20201101_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursebase',
            name='script',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
