# Generated by Django 2.2 on 2020-12-01 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0018_coursebase_script'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=6)),
                ('quiztype', models.CharField(max_length=4)),
                ('question', models.CharField(max_length=1000)),
                ('question_pic', models.FileField(blank=True, upload_to='quizpics')),
                ('question_textorcode', models.CharField(blank=True, max_length=5000)),
                ('option_1', models.CharField(blank=True, max_length=5000)),
                ('option_2', models.CharField(blank=True, max_length=5000)),
                ('option_3', models.CharField(blank=True, max_length=5000)),
                ('option_4', models.CharField(blank=True, max_length=5000)),
                ('answer', models.CharField(max_length=5000)),
                ('answer_explanation', models.CharField(blank=True, max_length=5000)),
                ('complexity', models.IntegerField()),
            ],
        ),
    ]
