# Generated by Django 2.2 on 2020-12-05 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0019_quizbase'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryExpCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=500)),
                ('lessonnum', models.CharField(max_length=6)),
                ('exp', models.IntegerField()),
                ('lives', models.IntegerField()),
                ('counter', models.IntegerField(default=1)),
            ],
        ),
    ]
