# Generated by Django 2.2 on 2020-12-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0020_temporaryexpcounter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemporaryExpCounter',
        ),
        migrations.AlterField(
            model_name='coursebase',
            name='video',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
