# Generated by Django 2.2 on 2022-01-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0021_auto_20201208_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='image_badge',
            field=models.CharField(blank=True, max_length=1000, verbose_name='image path'),
        ),
    ]
