# Generated by Django 2.2 on 2022-01-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0022_rating_image_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
