# Generated by Django 2.2 on 2022-01-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0023_auto_20220112_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='icon',
            field=models.FileField(blank=True, upload_to='levels/'),
        ),
    ]
