# Generated by Django 2.2 on 2022-01-12 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0024_rating_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursebase',
            name='lesson_name',
        ),
        migrations.RemoveField(
            model_name='coursebase',
            name='lessonid',
        ),
        migrations.RemoveField(
            model_name='coursebase',
            name='script',
        ),
        migrations.RemoveField(
            model_name='coursebase',
            name='video',
        ),
        migrations.AddField(
            model_name='coursebase',
            name='color',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='coursebase',
            name='complexity',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coursebase',
            name='courseid',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='coursebase',
            name='icon',
            field=models.FileField(blank=True, upload_to='lessonicons/'),
        ),
    ]
