# Generated by Django 2.2 on 2022-01-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0026_coursebase_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursebase',
            name='avaliable',
            field=models.BooleanField(default=False),
        ),
    ]
