# Generated by Django 2.2 on 2022-01-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0027_coursebase_avaliable'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursebase',
            name='authorid',
            field=models.IntegerField(blank=True, default=None),
            preserve_default=False,
        ),
    ]
