# Generated by Django 2.2 on 2022-01-12 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0028_coursebase_authorid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursebase',
            name='authorid',
        ),
    ]
