# Generated by Django 2.2 on 2022-01-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0029_remove_coursebase_authorid'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursebase',
            name='authorid',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
