# Generated by Django 2.2 on 2022-01-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0030_coursebase_authorid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursebase',
            name='authorid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
