# Generated by Django 2.2 on 2022-01-12 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0032_auto_20220112_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursebase',
            name='authorid',
        ),
    ]
