# Generated by Django 2.2 on 2022-01-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0033_remove_coursebase_authorid'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursebase',
            name='authorid',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
