# Generated by Django 2.2 on 2022-01-12 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0035_auto_20220112_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagsBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagid', models.IntegerField()),
                ('tag', models.CharField(max_length=50)),
            ],
        ),
    ]
