# Generated by Django 2.2 on 2022-01-12 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0036_tagsbase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseid', models.IntegerField()),
                ('tagid', models.IntegerField()),
            ],
        ),
    ]
