# Generated by Django 2.2 on 2022-02-03 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0037_course_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseid', models.IntegerField()),
                ('lessonid', models.IntegerField()),
                ('lesson_name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=5000)),
                ('materials', models.CharField(blank=True, max_length=5000)),
                ('script', models.CharField(blank=True, max_length=50000)),
                ('video', models.CharField(max_length=50)),
                ('prerequesite', models.IntegerField(blank=True)),
                ('avaliable', models.BooleanField(default=False)),
            ],
        ),
    ]
