# Generated by Django 2.2 on 2022-02-03 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0039_auto_20220203_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonbase',
            name='prerequesite',
            field=models.IntegerField(blank=True, default=''),
        ),
    ]
