# Generated by Django 2.2 on 2022-02-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0040_auto_20220203_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonbase',
            name='prerequesite',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
