# Generated by Django 2.2 on 2022-02-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0041_auto_20220203_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonbase',
            name='materials',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='lessonbase',
            name='script',
            field=models.TextField(blank=True, max_length=50000),
        ),
    ]
