# Generated by Django 2.2 on 2022-02-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0042_auto_20220204_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursebase',
            name='fontcolor',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
