# Generated by Django 2.2 on 2022-02-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0045_actiontypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonbase',
            name='quizcompleted',
            field=models.BooleanField(default=False),
        ),
    ]
