# Generated by Django 2.2 on 2022-02-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0047_remove_lessonbase_quizcompleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizbase',
            name='num',
        ),
        migrations.RemoveField(
            model_name='quizbase',
            name='question_textorcode',
        ),
        migrations.AddField(
            model_name='quizbase',
            name='courseid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizbase',
            name='lessonid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quizbase',
            name='question',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='quizbase',
            name='quiztype',
            field=models.IntegerField(),
        ),
    ]
