# Generated by Django 2.2 on 2022-02-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0048_auto_20220209_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursebase',
            name='benefits',
            field=models.TextField(blank=True, max_length=50000),
        ),
        migrations.AddField(
            model_name='coursebase',
            name='reqs',
            field=models.TextField(blank=True, max_length=50000),
        ),
    ]
