# Generated by Django 2.2 on 2022-02-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0049_auto_20220211_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempUserQuizDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('quizid', models.IntegerField()),
            ],
        ),
    ]
