# Generated by Django 2.2 on 2022-02-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0050_tempuserquizdict'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempCurrentQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('quizid', models.IntegerField()),
            ],
        ),
    ]
