# Generated by Django 2.2 on 2022-03-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0051_tempcurrentquiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuizProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('counter', models.IntegerField()),
                ('exp', models.IntegerField()),
            ],
        ),
    ]
