# Generated by Django 2.2 on 2022-03-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0052_userquizprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquizprogress',
            name='wrong',
            field=models.IntegerField(default=0),
        ),
    ]
