# Generated by Django 2.2 on 2022-03-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0053_userquizprogress_wrong'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizbase',
            name='code',
            field=models.TextField(blank=True, default='', max_length=10000),
        ),
    ]
