# Generated by Django 2.2 on 2022-03-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0054_quizbase_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursebase',
            name='language',
            field=models.TextField(blank=True, default='', max_length=5000),
        ),
    ]
