# Generated by Django 2.2 on 2022-03-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0055_coursebase_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugsMistakes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('link', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='', max_length=10000)),
                ('time', models.CharField(max_length=25)),
                ('checked', models.BooleanField(default=False)),
                ('testers', models.BooleanField(default=False)),
            ],
        ),
    ]
