# Generated by Django 2.2 on 2022-03-09 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0056_bugsmistakes'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('knowledge', models.CharField(max_length=150)),
                ('contact', models.CharField(max_length=150)),
                ('time', models.CharField(max_length=25)),
            ],
        ),
    ]
