# Generated by Django 2.2 on 2022-03-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0057_knowledgeshare'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('idea', models.TextField(blank=True, max_length=5000)),
                ('contact', models.CharField(max_length=150)),
                ('time', models.CharField(max_length=25)),
            ],
        ),
    ]
