# Generated by Django 2.2 on 2022-03-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0058_ideashare'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('est', models.IntegerField()),
                ('strength', models.TextField(blank=True, max_length=5000)),
                ('drawback', models.TextField(blank=True, max_length=5000)),
                ('time', models.CharField(max_length=25)),
            ],
        ),
    ]
