# Generated by Django 2.2 on 2020-12-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegMailCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=1000)),
                ('mailcode', models.CharField(max_length=4)),
            ],
        ),
    ]
