# Generated by Django 2.2 on 2022-01-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regmailcode',
            name='mailcode',
            field=models.CharField(max_length=8),
        ),
    ]
