# Generated by Django 2.2 on 2020-10-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('activity', models.CharField(max_length=1000, verbose_name='job')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('access_id', models.IntegerField(default=0, verbose_name='access id')),
                ('language', models.CharField(default='EN', max_length=2, verbose_name='language')),
                ('theme', models.IntegerField(default=0, verbose_name='theme')),
                ('image_path', models.CharField(max_length=1000, verbose_name='image path')),
                ('first_name', models.CharField(max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(max_length=50, verbose_name='last name')),
                ('city', models.CharField(default=None, max_length=50, verbose_name='city')),
                ('course_id', models.IntegerField(default=None, verbose_name='course_id')),
            ],
        ),
    ]
