# Generated by Django 2.2 on 2020-10-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='city',
            field=models.CharField(default='0', max_length=50, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='course_id',
            field=models.IntegerField(default=0, verbose_name='course_id'),
        ),
    ]
