# Generated by Django 2.2 on 2020-10-26 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_feed_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='password',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
    ]
