# Generated by Django 2.2 on 2020-10-27 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_feed_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_id', models.IntegerField()),
                ('access', models.CharField(max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='feed',
            name='access_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='feed.AccessLevel'),
        ),
    ]
