# Generated by Django 2.2 on 2020-10-27 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_auto_20201027_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='access_id',
        ),
    ]
