# Generated by Django 2.2 on 2020-10-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_remove_accesslevel_access_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslevel',
            name='accessid',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
