# Generated by Django 2.2 on 2020-10-27 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_accesslevel_accessid'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='accessid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='feed.AccessLevel'),
        ),
    ]
