# Generated by Django 2.2 on 2020-10-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0010_feed_accessid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='accessid',
            field=models.IntegerField(default=0),
        ),
    ]
