# Generated by Django 2.2 on 2020-12-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0015_auto_20201031_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='password',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
