# Generated by Django 2.2 on 2021-11-28 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0016_auto_20201205_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='image_path',
            field=models.CharField(blank=True, max_length=1000, verbose_name='image path'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
