# Generated by Django 2.2 on 2021-12-08 20:52

from django.db import migrations
import feed.formatChecker


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0017_auto_20211128_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountimage',
            name='file',
            field=feed.formatChecker.ContentTypeRestrictedFileField(upload_to='files/userpic/'),
        ),
    ]
