# Generated by Django 2.2 on 2021-12-08 21:20

from django.db import migrations
import feed.formatChecker


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0018_auto_20211208_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountimage',
            name='file',
            field=feed.formatChecker.ContentTypeRestrictedFileField(blank=True, null=True, upload_to='files/userpic/'),
        ),
    ]
