# Generated by Django 2.2 on 2021-12-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0019_auto_20211208_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='lvl',
            field=models.IntegerField(default=1),
        ),
    ]
