# Generated by Django 2.2 on 2021-12-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0020_feed_lvl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='lvl',
            field=models.IntegerField(default=0),
        ),
    ]
