# Generated by Django 2.2 on 2021-12-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0021_auto_20211212_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='login',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
