# Generated by Django 2.2 on 2021-12-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0022_feed_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='time',
            field=models.CharField(default='0', max_length=3),
        ),
    ]
