# Generated by Django 2.2 on 2021-12-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0023_feed_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite', models.CharField(max_length=20)),
                ('accessid', models.IntegerField(default=0)),
            ],
        ),
    ]
