# Generated by Django 2.2 on 2022-02-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0024_invites'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('courseid', models.IntegerField()),
                ('lessonid', models.IntegerField()),
                ('finished', models.BooleanField(default=False)),
            ],
        ),
    ]
