# Generated by Django 2.2 on 2022-02-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0027_feed_xpmodificator'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='lastactivity',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
