# Generated by Django 2.2 on 2022-02-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0028_feed_lastactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='lastactivity',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
