# Generated by Django 2.2 on 2022-03-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0029_auto_20220212_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='failed',
            field=models.BooleanField(default=False),
        ),
    ]
