# Generated by Django 2.2 on 2022-03-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0030_userprogress_failed'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='lasttraining',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
