# Generated by Django 2.2 on 2022-03-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0031_feed_lasttraining'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInterfaceStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('leftmenu', models.BooleanField(default=False)),
            ],
        ),
    ]
