# Generated by Django 2.2 on 2022-03-30 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0032_userinterfacestyle'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserErrorsHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('quizid', models.IntegerField()),
                ('time', models.CharField(blank=True, default='', max_length=30)),
            ],
        ),
    ]
