# Generated by Django 2.2 on 2021-12-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m2m', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromid', models.IntegerField()),
                ('toid', models.IntegerField()),
            ],
        ),
    ]
