# Generated by Django 2.2 on 2021-12-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m2m', '0002_friendlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=500)),
                ('time', models.DateTimeField()),
                ('roomid', models.IntegerField()),
                ('fromid', models.IntegerField()),
            ],
        ),
    ]
