# Generated by Django 2.2 on 2021-12-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m2m', '0005_messagebase_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessonid', models.IntegerField(blank=True)),
            ],
        ),
    ]
