# Generated by Django 2.2 on 2021-12-14 06:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m2m', '0006_usercourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='courseid',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='usercourse',
            name='startdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='usercourse',
            name='userid',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='lessonid',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
