# Generated by Django 2.2 on 2021-12-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m2m', '0007_auto_20211214_0629'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromid', models.IntegerField()),
                ('toid', models.IntegerField()),
            ],
        ),
    ]
